### ISSUE TITLE
Crash parsing BBa_T9002 example

### ISSUE THREAD

**Issue by udp** [SynBioDex/libSBOLj#145]
BBa_T9002.xml from the examples directory crashes libSBOLj core2 (develop branch) with a null pointer exception in `addChildSafely`.  This is caused by `parseSequenceAnnotation` adding a null location to the locations array.

**Comment by cjmyers** [comment]
Good catch.  There was a bug when converting a precedes relationship that did not have an strand indication.  This has been fixed and committed.  I've also added these two examples to the JUnit test suite.  Please test and if if it works for you, please close this issue.

**Comment by udp** [comment]
Thanks - that fixed the null pointer exception, but revealed an issue with BBa_T9002 itself.  The annotation:

      <s:annotation>
       <s:SequenceAnnotation rdf:about="http://partsregistry.org/anot/an_5591_5114_1">
        <s:precedes rdf:resource="http://partsregistry.org/anot/an_5591_5339_2"/>
        <s:subComponent>
         <s:DnaComponent rdf:about="http://partsregistry.org/part/BBa_F2620">
          <s:displayId>BBa_F2620</s:displayId>
          <s:description>3OC&lt;sub&gt;6&lt;/sub&gt;HSL -&gt; PoPS Receiver</s:description>
          <rdf:type rdf:resource="http://purl.obolibrary.org/obo/signalling"/>
         </s:DnaComponent>
        </s:subComponent>
       </s:SequenceAnnotation>
      </s:annotation>

is present twice in the file, causing the following error:

    java.lang.IllegalArgumentException: Instance for identity `http://partsregistry.org/anot/an_5591_5114_1' exists for a sequenceAnnotation
        at org.sbolstandard.core2.Identified.addChildSafely(Identified.java:516)
        at org.sbolstandard.core2.ComponentDefinition.addSequenceAnnotation(ComponentDefinition.java:698)
        at org.sbolstandard.core2.ComponentDefinition.setSequenceAnnotations(ComponentDefinition.java:786)
        at org.sbolstandard.core2.SBOLReader.parseDnaComponentV1(SBOLReader.java:639)
        at org.sbolstandard.core2.SBOLReader.readTopLevelDocsV1(SBOLReader.java:466)
        at org.sbolstandard.core2.SBOLReader.readV1(SBOLReader.java:430)
        at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:307)

**Comment by udp** [comment]
PR opened #148
