### ISSUE TITLE
Problems with JSON and Turtle Parsers

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOLj#238]
There are some problems with JSON and Turtle Parsers (see below).  If not fixed before release, then these parsers must be made package private.

Hi Matthew and Goksel,

We found a bug on your Turtle parser today, and we'd like to make a feature request on your JSON parser. We found these issues by calling read and write methods specified in file GettingStartedExample.java located at the develop branch on github: https://github.com/SynBioDex/libSBOLj/tree/develop/examples/src/main/java/org/sbolstandard/core2/examples. 

1. The Turtle parser generates an illegal argument exception on the first URI after declarations of prefixes in a Turtle file. In this example, the exception occurs for the URI of the component definition TetR_promoter_copy. This promoter is created by copying the TetR_pomoter, but it is given a different display ID of "BBa_K137046". Its URI is http://partsregistry.org/BBa_K137046. The error stack is pasted below. To recreate this error, comment out lines 166 and 167 in the writeThenRead(SBOLDocument) method, and uncomment lines 170 and 171 to have it write and then read in Turtle format.

Exception in thread "main" java.lang.IllegalArgumentException: Next token does not match expected pattern at `<http://partsregistry.org/BBa_K137046>`
    at uk.ac.intbio.core.io.turtle.TurtleIo$WSScanner.next(TurtleIo.java:486)
    at uk.ac.intbio.core.io.turtle.TurtleIo$2.readPfxURI(TurtleIo.java:347)
    at uk.ac.intbio.core.io.turtle.TurtleIo$2.readTLDs(TurtleIo.java:247)
    at uk.ac.intbio.core.io.turtle.TurtleIo$2.read(TurtleIo.java:234)
    at org.sbolstandard.core2.SBOLReader.readTurtle(SBOLReader.java:471)
    at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:385)
    at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:371)
    at org.sbolstandard.core2.examples.GettingStartedExample.writeThenRead(GettingStartedExample.java:171)
    at org.sbolstandard.core2.examples.GettingStartedExample.main(GettingStartedExample.java:156)

2. Collect namespaces in JSON parser. It seems that the JSON output file does not have namespace bindings like a RDF/XML file. It instead uses a inline style for all namespaces. It would be nice if the JSON parser collects them so that they can be used by our reader. This is also needed if we read in a JSON file, and want to output a RDF. Although SBOLDocument class adds several default namespaces, it won't know any custom ones that are specified in the JSON input file. Currently, our reader generates an exception because it could not find either the namespace for sbol1 or sbo2. To recreate this issue, comment out lines 166 and 167 in the writeThenRead(SBOLDocument) method, and uncomment lines 174 and 175 to have it write and then read in JSON format.

Please let me know if my email is not clear. Thanks.

Regards,
Zhen

**Comment by cjmyers** [comment]
This have been made package private until fixed in sbol-data.
