### ISSUE TITLE
2.1.1 Validator shows differences with completed tutorial

### ISSUE THREAD

**Issue by minnatwang** [SynBioDex/libSBOLj#427]
Ran the attached code with SBOLValidate against the example code and received these errors: 

![image](https://cloud.githubusercontent.com/assets/8450790/21461307/bf8a3382-c90d-11e6-85c3-b346a72615c0.png)

But when @cjmyers validated the code on the Validator webapp, no errors came up.

[CopyOfRepressionModel.java.zip](https://github.com/SynBioDex/libSBOLj/files/671382/CopyOfRepressionModel.java.zip)

(I'll validate the code against the libSBOLj_demo and update this comment with the results)

**Comment by cjmyers** [comment]
Minna: did you ever verify it this problem occurs in the libSBOLj_demo?

**Comment by mehersam** [comment]
Running the RepressionModel in libSBOLj-demo throws a validation error for adding a namespace to the document: doc.addNamespace(URI.create(prURI) , prPrefix);
 
Exception in thread "main" org.sbolstandard.core2.SBOLValidationException: sbol-10105: An SBOL document MUST be serialized as a well-formed RDF/XML file that adheres to the grammar defined by: “https://www.w3.org/TR/rdf-syntax-grammar/” 
Reference: SBOL Version 2.1.0 Section 10 on page 58
	at org.sbolstandard.core2.SBOLDocument.addNamespaceBinding(SBOLDocument.java:2146)
	at org.sbolstandard.core2.SBOLDocument.addNamespace(SBOLDocument.java:2127)
	at org.sbolstandard.core2.examples.RepressionModel.main(RepressionModel.java:352)

**Comment by mehersam** [comment]
libSBOLj_demo validates correctly both through the library and the online web app. Closing issue.
