### ISSUE TITLE
Opaque failure while reading GenBank

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/libSBOLj#623]
Importing this genbank file produces an opaque error: 
[Other_GenBank_imports.txt](https://github.com/SynBioDex/libSBOLj/files/7190708/Other_GenBank_imports.txt)
The GenBank file parses correctly with BioPython

````
Converting GenBank to SBOL Version 2 Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1 at org.sbolstandard.core2.GenBank.read(GenBank.java:1334) at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:700) at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:625) at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:512) at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:437) at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:422) at org.sbolstandard.core2.SBOLValidate.validate(SBOLValidate.java:2726) at org.sbolstandard.core2.SBOLValidate.main(SBOLValidate.java:3028)
````

**Comment by jakebeal** [comment]
The triggering issue, BTW, is apparently that line 9602 in the file had an extra newline.
I think you're not really supposed to to this, but other GenBank parsers are tolerant of this and libSBOLj is not.
